ICEHOCKEY_PLAYERS = [
    {
        "id": "icehockey_player_connor_mcdavid",
        "type": "player",
        "value": "Connor McDavid",
        "aliases": [
            "Connor McDavid",
            "McDavid",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "team": "Edmonton Oilers",
            "league": "NHL",
            "position": "Center",
            "jersey": "97",
            "country": "Canada",
            "shoots": "Left",
        },
    },
    {
        "id": "icehockey_player_leon_draisaitl",
        "type": "player",
        "value": "Leon Draisaitl",
        "aliases": [
            "Leon Draisaitl",
            "Draisaitl",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "team": "Edmonton Oilers",
            "league": "NHL",
            "position": "Center",
            "jersey": "29",
            "country": "Germany",
            "shoots": "Left",
        },
    },
    {
        "id": "icehockey_player_nathan_mackinnon",
        "type": "player",
        "value": "Nathan MacKinnon",
        "aliases": [
            "Nathan MacKinnon",
            "MacKinnon",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "team": "Colorado Avalanche",
            "league": "NHL",
            "position": "Center",
            "jersey": "29",
            "country": "Canada",
            "shoots": "Right",
        },
    },
    {
        "id": "icehockey_player_cale_makar",
        "type": "player",
        "value": "Cale Makar",
        "aliases": [
            "Cale Makar",
            "Makar",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "team": "Colorado Avalanche",
            "league": "NHL",
            "position": "Defenseman",
            "jersey": "8",
            "country": "Canada",
            "shoots": "Right",
        },
    },
    {
        "id": "icehockey_player_auston_matthews",
        "type": "player",
        "value": "Auston Matthews",
        "aliases": [
            "Auston Matthews",
            "Matthews",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "team": "Toronto Maple Leafs",
            "league": "NHL",
            "position": "Center",
            "jersey": "34",
            "country": "USA",
            "shoots": "Left",
        },
    },
    {
        "id": "icehockey_player_mitch_marner",
        "type": "player",
        "value": "Mitch Marner",
        "aliases": [
            "Mitch Marner",
            "Marner",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "team": "Vegas Golden Knights",
            "league": "NHL",
            "position": "Right Wing",
            "jersey": "93",
            "country": "Canada",
            "shoots": "Right",
        },
    },
    {
        "id": "icehockey_player_sidney_crosby",
        "type": "player",
        "value": "Sidney Crosby",
        "aliases": [
            "Sidney Crosby",
            "Crosby",
            "Sid",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "team": "Pittsburgh Penguins",
            "league": "NHL",
            "position": "Center",
            "jersey": "87",
            "country": "Canada",
            "shoots": "Left",
        },
    },
    {
        "id": "icehockey_player_alexander_ovechkin",
        "type": "player",
        "value": "Alexander Ovechkin",
        "aliases": [
            "Alexander Ovechkin",
            "Alex Ovechkin",
            "Ovechkin",
            "Ovi",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "team": "Washington Capitals",
            "league": "NHL",
            "position": "Left Wing",
            "jersey": "8",
            "country": "Russia",
            "shoots": "Right",
        },
    },
    {
        "id": "icehockey_player_nikita_kucherov",
        "type": "player",
        "value": "Nikita Kucherov",
        "aliases": [
            "Nikita Kucherov",
            "Kucherov",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "team": "Tampa Bay Lightning",
            "league": "NHL",
            "position": "Right Wing",
            "jersey": "86",
            "country": "Russia",
            "shoots": "Left",
        },
    },
    {
        "id": "icehockey_player_david_pastrnak",
        "type": "player",
        "value": "David Pastrňák",
        "aliases": [
            "David Pastrňák",
            "David Pastrnak",
            "Pastrnak",
            "Pasta",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "team": "Boston Bruins",
            "league": "NHL",
            "position": "Right Wing",
            "jersey": "88",
            "country": "Czech Republic",
            "shoots": "Right",
        },
    },
    {
        "id": "icehockey_player_igor_shesterkin",
        "type": "player",
        "value": "Igor Shesterkin",
        "aliases": [
            "Igor Shesterkin",
            "Shesterkin",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "team": "New York Rangers",
            "league": "NHL",
            "position": "Goaltender",
            "jersey": "31",
            "country": "Russia",
            "shoots": "Left",
        },
    },
    {
        "id": "icehockey_player_jack_eichel",
        "type": "player",
        "value": "Jack Eichel",
        "aliases": [
            "Jack Eichel",
            "Eichel",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "team": "Vegas Golden Knights",
            "league": "NHL",
            "position": "Center",
            "jersey": "9",
            "country": "USA",
            "shoots": "Right",
        },
    },
    {
        "id": "icehockey_player_matthew_tkachuk",
        "type": "player",
        "value": "Matthew Tkachuk",
        "aliases": [
            "Matthew Tkachuk",
            "Tkachuk",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "team": "Florida Panthers",
            "league": "NHL",
            "position": "Left Wing",
            "jersey": "19",
            "country": "USA",
            "shoots": "Left",
        },
    },
    {
        "id": "icehockey_player_sam_reinhart",
        "type": "player",
        "value": "Sam Reinhart",
        "aliases": [
            "Sam Reinhart",
            "Reinhart",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "team": "Florida Panthers",
            "league": "NHL",
            "position": "Center",
            "jersey": "13",
            "country": "Canada",
            "shoots": "Right",
        },
    },
    {
        "id": "icehockey_player_sergei_bobrovsky",
        "type": "player",
        "value": "Sergei Bobrovsky",
        "aliases": [
            "Sergei Bobrovsky",
            "Bobrovsky",
            "Bob",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "team": "Florida Panthers",
            "league": "NHL",
            "position": "Goaltender",
            "jersey": "72",
            "country": "Russia",
            "shoots": "Left",
        },
    },
]