ICEHOCKEY_TEAMS = [
    # ==========================================
    # Atlantic Division
    # ==========================================
    {
        "id": "icehockey_team_boston_bruins",
        "type": "team",
        "value": "Boston Bruins",
        "aliases": [
            "Boston Bruins",
            "Bruins",
            "BOS",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "league": "NHL",
            "conference": "Eastern",
            "division": "Atlantic",
            "city": "Boston",
            "country": "USA",
            "abbreviation": "BOS",
            "arena": "TD Garden",
        },
    },
    {
        "id": "icehockey_team_buffalo_sabres",
        "type": "team",
        "value": "Buffalo Sabres",
        "aliases": [
            "Buffalo Sabres",
            "Sabres",
            "BUF",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "league": "NHL",
            "conference": "Eastern",
            "division": "Atlantic",
            "city": "Buffalo",
            "country": "USA",
            "abbreviation": "BUF",
            "arena": "KeyBank Center",
        },
    },
    {
        "id": "icehockey_team_detroit_red_wings",
        "type": "team",
        "value": "Detroit Red Wings",
        "aliases": [
            "Detroit Red Wings",
            "Red Wings",
            "DET",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "league": "NHL",
            "conference": "Eastern",
            "division": "Atlantic",
            "city": "Detroit",
            "country": "USA",
            "abbreviation": "DET",
            "arena": "Little Caesars Arena",
        },
    },
    {
        "id": "icehockey_team_florida_panthers",
        "type": "team",
        "value": "Florida Panthers",
        "aliases": [
            "Florida Panthers",
            "Panthers",
            "FLA",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "league": "NHL",
            "conference": "Eastern",
            "division": "Atlantic",
            "city": "Sunrise",
            "country": "USA",
            "abbreviation": "FLA",
            "arena": "Amerant Bank Arena",
        },
    },
    {
        "id": "icehockey_team_montreal_canadiens",
        "type": "team",
        "value": "Montreal Canadiens",
        "aliases": [
            "Montreal Canadiens",
            "Canadiens",
            "Habs",
            "MTL",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "league": "NHL",
            "conference": "Eastern",
            "division": "Atlantic",
            "city": "Montreal",
            "country": "Canada",
            "abbreviation": "MTL",
            "arena": "Bell Centre",
        },
    },
    {
        "id": "icehockey_team_ottawa_senators",
        "type": "team",
        "value": "Ottawa Senators",
        "aliases": [
            "Ottawa Senators",
            "Senators",
            "OTT",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "league": "NHL",
            "conference": "Eastern",
            "division": "Atlantic",
            "city": "Ottawa",
            "country": "Canada",
            "abbreviation": "OTT",
            "arena": "Canadian Tire Centre",
        },
    },
    {
        "id": "icehockey_team_tampa_bay_lightning",
        "type": "team",
        "value": "Tampa Bay Lightning",
        "aliases": [
            "Tampa Bay Lightning",
            "Lightning",
            "TB",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "league": "NHL",
            "conference": "Eastern",
            "division": "Atlantic",
            "city": "Tampa",
            "country": "USA",
            "abbreviation": "TB",
            "arena": "Amalie Arena",
        },
    },
    {
        "id": "icehockey_team_toronto_maple_leafs",
        "type": "team",
        "value": "Toronto Maple Leafs",
        "aliases": [
            "Toronto Maple Leafs",
            "Maple Leafs",
            "Leafs",
            "TOR",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "league": "NHL",
            "conference": "Eastern",
            "division": "Atlantic",
            "city": "Toronto",
            "country": "Canada",
            "abbreviation": "TOR",
            "arena": "Scotiabank Arena",
        },
    },

    # ==========================================
    # Metropolitan Division
    # ==========================================
    {
        "id": "icehockey_team_carolina_hurricanes",
        "type": "team",
        "value": "Carolina Hurricanes",
        "aliases": [
            "Carolina Hurricanes",
            "Hurricanes",
            "Canes",
            "CAR",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "league": "NHL",
            "conference": "Eastern",
            "division": "Metropolitan",
            "city": "Raleigh",
            "country": "USA",
            "abbreviation": "CAR",
            "arena": "Lenovo Center",
        },
    },
    {
        "id": "icehockey_team_new_jersey_devils",
        "type": "team",
        "value": "New Jersey Devils",
        "aliases": [
            "New Jersey Devils",
            "Devils",
            "NJD",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "league": "NHL",
            "conference": "Eastern",
            "division": "Metropolitan",
            "city": "Newark",
            "country": "USA",
            "abbreviation": "NJD",
            "arena": "Prudential Center",
        },
    },
    {
        "id": "icehockey_team_new_york_rangers",
        "type": "team",
        "value": "New York Rangers",
        "aliases": [
            "New York Rangers",
            "Rangers",
            "NYR",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "league": "NHL",
            "conference": "Eastern",
            "division": "Metropolitan",
            "city": "New York",
            "country": "USA",
            "abbreviation": "NYR",
            "arena": "Madison Square Garden",
        },
    },
    {
        "id": "icehockey_team_pittsburgh_penguins",
        "type": "team",
        "value": "Pittsburgh Penguins",
        "aliases": [
            "Pittsburgh Penguins",
            "Penguins",
            "Pens",
            "PIT",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "league": "NHL",
            "conference": "Eastern",
            "division": "Metropolitan",
            "city": "Pittsburgh",
            "country": "USA",
            "abbreviation": "PIT",
            "arena": "PPG Paints Arena",
        },
    },
    {
        "id": "icehockey_team_washington_capitals",
        "type": "team",
        "value": "Washington Capitals",
        "aliases": [
            "Washington Capitals",
            "Capitals",
            "Caps",
            "WSH",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "league": "NHL",
            "conference": "Eastern",
            "division": "Metropolitan",
            "city": "Washington",
            "country": "USA",
            "abbreviation": "WSH",
            "arena": "Capital One Arena",
        },
    },

    # ==========================================
    # Central Division
    # ==========================================
    {
        "id": "icehockey_team_colorado_avalanche",
        "type": "team",
        "value": "Colorado Avalanche",
        "aliases": [
            "Colorado Avalanche",
            "Avalanche",
            "Avs",
            "COL",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "league": "NHL",
            "conference": "Western",
            "division": "Central",
            "city": "Denver",
            "country": "USA",
            "abbreviation": "COL",
            "arena": "Ball Arena",
        },
    },
    {
        "id": "icehockey_team_dallas_stars",
        "type": "team",
        "value": "Dallas Stars",
        "aliases": [
            "Dallas Stars",
            "Stars",
            "DAL",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "league": "NHL",
            "conference": "Western",
            "division": "Central",
            "city": "Dallas",
            "country": "USA",
            "abbreviation": "DAL",
            "arena": "American Airlines Center",
        },
    },
    {
        "id": "icehockey_team_winnipeg_jets",
        "type": "team",
        "value": "Winnipeg Jets",
        "aliases": [
            "Winnipeg Jets",
            "Jets",
            "WPG",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "league": "NHL",
            "conference": "Western",
            "division": "Central",
            "city": "Winnipeg",
            "country": "Canada",
            "abbreviation": "WPG",
            "arena": "Canada Life Centre",
        },
    },

    # ==========================================
    # Pacific Division
    # ==========================================
    {
        "id": "icehockey_team_edmonton_oilers",
        "type": "team",
        "value": "Edmonton Oilers",
        "aliases": [
            "Edmonton Oilers",
            "Oilers",
            "EDM",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "league": "NHL",
            "conference": "Western",
            "division": "Pacific",
            "city": "Edmonton",
            "country": "Canada",
            "abbreviation": "EDM",
            "arena": "Rogers Place",
        },
    },
    {
        "id": "icehockey_team_vegas_golden_knights",
        "type": "team",
        "value": "Vegas Golden Knights",
        "aliases": [
            "Vegas Golden Knights",
            "Golden Knights",
            "VGK",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "league": "NHL",
            "conference": "Western",
            "division": "Pacific",
            "city": "Las Vegas",
            "country": "USA",
            "abbreviation": "VGK",
            "arena": "T-Mobile Arena",
        },
    },
    {
        "id": "icehockey_team_los_angeles_kings",
        "type": "team",
        "value": "Los Angeles Kings",
        "aliases": [
            "Los Angeles Kings",
            "Kings",
            "LA Kings",
            "LAK",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "league": "NHL",
            "conference": "Western",
            "division": "Pacific",
            "city": "Los Angeles",
            "country": "USA",
            "abbreviation": "LAK",
            "arena": "Crypto.com Arena",
        },
    },
    {
        "id": "icehockey_team_vancouver_canucks",
        "type": "team",
        "value": "Vancouver Canucks",
        "aliases": [
            "Vancouver Canucks",
            "Canucks",
            "VAN",
        ],
        "sport": "Ice Hockey",
        "metadata": {
            "league": "NHL",
            "conference": "Western",
            "division": "Pacific",
            "city": "Vancouver",
            "country": "Canada",
            "abbreviation": "VAN",
            "arena": "Rogers Arena",
        },
    },
]