GOLF_PLAYERS = [
    {
        "id": "golf_player_scottie_scheffler",
        "type": "player",
        "value": "Scottie Scheffler",
        "aliases": [
            "Scottie Scheffler",
            "Scheffler",
        ],
        "sport": "Golf",
        "metadata": {
            "tour": "PGA Tour",
            "country": "USA",
            "handedness": "Right",
            "turned_pro": "2018",
        },
    },
    {
        "id": "golf_player_rory_mcilroy",
        "type": "player",
        "value": "Rory McIlroy",
        "aliases": [
            "Rory McIlroy",
            "McIlroy",
            "Rory",
        ],
        "sport": "Golf",
        "metadata": {
            "tour": "PGA Tour",
            "country": "Northern Ireland",
            "handedness": "Right",
            "turned_pro": "2007",
        },
    },
    {
        "id": "golf_player_jon_rahm",
        "type": "player",
        "value": "Jon Rahm",
        "aliases": [
            "Jon Rahm",
            "Rahm",
        ],
        "sport": "Golf",
        "metadata": {
            "tour": "LIV Golf",
            "country": "Spain",
            "handedness": "Right",
            "turned_pro": "2016",
        },
    },
    {
        "id": "golf_player_xander_schauffele",
        "type": "player",
        "value": "Xander Schauffele",
        "aliases": [
            "Xander Schauffele",
            "Schauffele",
            "Xander",
        ],
        "sport": "Golf",
        "metadata": {
            "tour": "PGA Tour",
            "country": "USA",
            "handedness": "Right",
            "turned_pro": "2015",
        },
    },
    {
        "id": "golf_player_collin_morikawa",
        "type": "player",
        "value": "Collin Morikawa",
        "aliases": [
            "Collin Morikawa",
            "Morikawa",
        ],
        "sport": "Golf",
        "metadata": {
            "tour": "PGA Tour",
            "country": "USA",
            "handedness": "Right",
            "turned_pro": "2019",
        },
    },
    {
        "id": "golf_player_bryson_dechambeau",
        "type": "player",
        "value": "Bryson DeChambeau",
        "aliases": [
            "Bryson DeChambeau",
            "DeChambeau",
            "Bryson",
        ],
        "sport": "Golf",
        "metadata": {
            "tour": "LIV Golf",
            "country": "USA",
            "handedness": "Right",
            "turned_pro": "2016",
        },
    },
    {
        "id": "golf_player_brooks_koepka",
        "type": "player",
        "value": "Brooks Koepka",
        "aliases": [
            "Brooks Koepka",
            "Koepka",
        ],
        "sport": "Golf",
        "metadata": {
            "tour": "LIV Golf",
            "country": "USA",
            "handedness": "Right",
            "turned_pro": "2012",
        },
    },
    {
        "id": "golf_player_justin_thomas",
        "type": "player",
        "value": "Justin Thomas",
        "aliases": [
            "Justin Thomas",
            "JT",
            "Thomas",
        ],
        "sport": "Golf",
        "metadata": {
            "tour": "PGA Tour",
            "country": "USA",
            "handedness": "Right",
            "turned_pro": "2013",
        },
    },
    {
        "id": "golf_player_jordan_spieth",
        "type": "player",
        "value": "Jordan Spieth",
        "aliases": [
            "Jordan Spieth",
            "Spieth",
        ],
        "sport": "Golf",
        "metadata": {
            "tour": "PGA Tour",
            "country": "USA",
            "handedness": "Right",
            "turned_pro": "2012",
        },
    },
    {
        "id": "golf_player_viktor_hovland",
        "type": "player",
        "value": "Viktor Hovland",
        "aliases": [
            "Viktor Hovland",
            "Hovland",
        ],
        "sport": "Golf",
        "metadata": {
            "tour": "PGA Tour",
            "country": "Norway",
            "handedness": "Right",
            "turned_pro": "2019",
        },
    },
    {
        "id": "golf_player_tommy_fleetwood",
        "type": "player",
        "value": "Tommy Fleetwood",
        "aliases": [
            "Tommy Fleetwood",
            "Fleetwood",
        ],
        "sport": "Golf",
        "metadata": {
            "tour": "DP World Tour",
            "country": "England",
            "handedness": "Right",
            "turned_pro": "2010",
        },
    },
    {
        "id": "golf_player_ludvig_aberg",
        "type": "player",
        "value": "Ludvig Åberg",
        "aliases": [
            "Ludvig Åberg",
            "Ludvig Aberg",
            "Åberg",
            "Aberg",
        ],
        "sport": "Golf",
        "metadata": {
            "tour": "PGA Tour",
            "country": "Sweden",
            "handedness": "Right",
            "turned_pro": "2023",
        },
    },
    {
        "id": "golf_player_hideki_matsuyama",
        "type": "player",
        "value": "Hideki Matsuyama",
        "aliases": [
            "Hideki Matsuyama",
            "Matsuyama",
        ],
        "sport": "Golf",
        "metadata": {
            "tour": "PGA Tour",
            "country": "Japan",
            "handedness": "Right",
            "turned_pro": "2013",
        },
    },
    {
        "id": "golf_player_min_woo_lee",
        "type": "player",
        "value": "Min Woo Lee",
        "aliases": [
            "Min Woo Lee",
            "Lee",
        ],
        "sport": "Golf",
        "metadata": {
            "tour": "PGA Tour",
            "country": "Australia",
            "handedness": "Right",
            "turned_pro": "2019",
        },
    },
    {
        "id": "golf_player_phil_mickelson",
        "type": "player",
        "value": "Phil Mickelson",
        "aliases": [
            "Phil Mickelson",
            "Mickelson",
            "Lefty",
        ],
        "sport": "Golf",
        "metadata": {
            "tour": "LIV Golf",
            "country": "USA",
            "handedness": "Left",
            "turned_pro": "1992",
        },
    },
]