"""
Entity APIs

Expose intelligence generated by PulseIQ.

Endpoints:
- Top entities
- Entities for an article
- Articles for an entity
- Search entities
"""

from fastapi import APIRouter

from database.entity_repo import (
    get_top_entities,
    get_entities_for_article,
    get_articles_for_entity,
    search_entities,
)

router = APIRouter(
    prefix="/entities",
    tags=["Entities"],
)


# -----------------------------------------------------
# Top Entities
# -----------------------------------------------------

@router.get("/top")
def top_entities(limit: int = 10):
    """
    Return the most mentioned entities.
    """

    rows = get_top_entities(limit)

    return [
        {
            "entity_id": row[0],
            "mentions": row[1],
        }
        for row in rows
    ]


# -----------------------------------------------------
# Entities for an Article
# -----------------------------------------------------

@router.get("/article/{article_id}")
def article_entities(article_id: int):
    """
    Return all resolved entities for a given article.
    """

    rows = get_entities_for_article(article_id)

    return [
        {
            "entity_id": row[0],
            "matched_alias": row[1],
            "confidence": row[2],
            "created_at": row[3],
        }
        for row in rows
    ]


# -----------------------------------------------------
# Articles mentioning an Entity
# -----------------------------------------------------

@router.get("/{entity_id}")
def entity_articles(entity_id: str):
    """
    Return all articles mentioning an entity.
    """

    rows = get_articles_for_entity(entity_id)

    return [
        {
            "article_id": row[0],
            "title": row[1],
            "source": row[2],
            "published_at": row[3],
        }
        for row in rows
    ]


# -----------------------------------------------------
# Search Entities
# -----------------------------------------------------

@router.get("/search/{text}")
def search(text: str):
    """
    Search entities by entity_id.
    """

    rows = search_entities(text)

    return [
        {
            "entity_id": row[0],
            "mentions": row[1],
        }
        for row in rows
    ]