import { FiClock } from "react-icons/fi";
import Panel from "../../../common/Panel/Panel";
import "./TimelineSection.css";

export default function TimelineSection() {
    return (
        <Panel title="Attention Timeline">

            <div className="timeline-placeholder">

                <FiClock className="timeline-icon" />

                <div>

                    <strong>Historical Timeline Coming Soon</strong>

                    <p>
                        Timeline snapshots are already generated by the
                        Attention Engine. This section will visualize
                        attention movement, ranking changes, and major
                        events across time.
                    </p>

                </div>

            </div>

        </Panel>
    );
}