BASEBALL_PLAYERS = [
    {
        "id": "baseball_player_shohei_ohtani",
        "type": "player",
        "value": "Shohei Ohtani",
        "aliases": [
            "Shohei Ohtani",
            "Ohtani",
            "Shotime",
        ],
        "sport": "Baseball",
        "metadata": {
            "team": "Los Angeles Dodgers",
            "league": "MLB",
            "position": "Designated Hitter / Pitcher",
            "bats": "Left",
            "throws": "Right",
            "country": "Japan",
        },
    },
    {
        "id": "baseball_player_aaron_judge",
        "type": "player",
        "value": "Aaron Judge",
        "aliases": [
            "Aaron Judge",
            "Judge",
            "All Rise",
        ],
        "sport": "Baseball",
        "metadata": {
            "team": "New York Yankees",
            "league": "MLB",
            "position": "Outfielder",
            "bats": "Right",
            "throws": "Right",
            "country": "USA",
        },
    },
    {
        "id": "baseball_player_mookie_betts",
        "type": "player",
        "value": "Mookie Betts",
        "aliases": [
            "Mookie Betts",
            "Mookie",
            "Betts",
        ],
        "sport": "Baseball",
        "metadata": {
            "team": "Los Angeles Dodgers",
            "league": "MLB",
            "position": "Shortstop / Outfielder",
            "bats": "Right",
            "throws": "Right",
            "country": "USA",
        },
    },
    {
        "id": "baseball_player_freddie_freeman",
        "type": "player",
        "value": "Freddie Freeman",
        "aliases": [
            "Freddie Freeman",
            "Freeman",
        ],
        "sport": "Baseball",
        "metadata": {
            "team": "Los Angeles Dodgers",
            "league": "MLB",
            "position": "First Baseman",
            "bats": "Left",
            "throws": "Right",
            "country": "Canada",
        },
    },
    {
        "id": "baseball_player_juan_soto",
        "type": "player",
        "value": "Juan Soto",
        "aliases": [
            "Juan Soto",
            "Soto",
        ],
        "sport": "Baseball",
        "metadata": {
            "team": "New York Mets",
            "league": "MLB",
            "position": "Outfielder",
            "bats": "Left",
            "throws": "Left",
            "country": "Dominican Republic",
        },
    },
    {
        "id": "baseball_player_bryce_harper",
        "type": "player",
        "value": "Bryce Harper",
        "aliases": [
            "Bryce Harper",
            "Harper",
        ],
        "sport": "Baseball",
        "metadata": {
            "team": "Philadelphia Phillies",
            "league": "MLB",
            "position": "First Baseman",
            "bats": "Left",
            "throws": "Right",
            "country": "USA",
        },
    },
    {
        "id": "baseball_player_ronald_acuna_jr",
        "type": "player",
        "value": "Ronald Acuña Jr.",
        "aliases": [
            "Ronald Acuña Jr.",
            "Ronald Acuna Jr",
            "Acuna",
        ],
        "sport": "Baseball",
        "metadata": {
            "team": "Atlanta Braves",
            "league": "MLB",
            "position": "Outfielder",
            "bats": "Right",
            "throws": "Right",
            "country": "Venezuela",
        },
    },
    {
        "id": "baseball_player_jose_altuve",
        "type": "player",
        "value": "José Altuve",
        "aliases": [
            "José Altuve",
            "Jose Altuve",
            "Altuve",
        ],
        "sport": "Baseball",
        "metadata": {
            "team": "Houston Astros",
            "league": "MLB",
            "position": "Second Baseman",
            "bats": "Right",
            "throws": "Right",
            "country": "Venezuela",
        },
    },
    {
        "id": "baseball_player_francisco_lindor",
        "type": "player",
        "value": "Francisco Lindor",
        "aliases": [
            "Francisco Lindor",
            "Lindor",
        ],
        "sport": "Baseball",
        "metadata": {
            "team": "New York Mets",
            "league": "MLB",
            "position": "Shortstop",
            "bats": "Switch",
            "throws": "Right",
            "country": "Puerto Rico",
        },
    },
    {
        "id": "baseball_player_gerrit_cole",
        "type": "player",
        "value": "Gerrit Cole",
        "aliases": [
            "Gerrit Cole",
            "Cole",
        ],
        "sport": "Baseball",
        "metadata": {
            "team": "New York Yankees",
            "league": "MLB",
            "position": "Pitcher",
            "bats": "Right",
            "throws": "Right",
            "country": "USA",
        },
    },
    {
        "id": "baseball_player_mike_trout",
        "type": "player",
        "value": "Mike Trout",
        "aliases": [
            "Mike Trout",
            "Trout",
        ],
        "sport": "Baseball",
        "metadata": {
            "team": "Los Angeles Angels",
            "league": "MLB",
            "position": "Outfielder",
            "bats": "Right",
            "throws": "Right",
            "country": "USA",
        },
    },
    {
        "id": "baseball_player_paul_skenes",
        "type": "player",
        "value": "Paul Skenes",
        "aliases": [
            "Paul Skenes",
            "Skenes",
        ],
        "sport": "Baseball",
        "metadata": {
            "team": "Pittsburgh Pirates",
            "league": "MLB",
            "position": "Pitcher",
            "bats": "Right",
            "throws": "Right",
            "country": "USA",
        },
    },
]