BASEBALL_TEAMS = [
    # ==========================================
    # American League East
    # ==========================================
    {
        "id": "baseball_team_new_york_yankees",
        "type": "team",
        "value": "New York Yankees",
        "aliases": [
            "New York Yankees",
            "Yankees",
            "NYY",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "American League",
            "division": "East",
            "city": "New York",
            "country": "USA",
            "abbreviation": "NYY",
        },
    },
    {
        "id": "baseball_team_boston_red_sox",
        "type": "team",
        "value": "Boston Red Sox",
        "aliases": [
            "Boston Red Sox",
            "Red Sox",
            "BOS",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "American League",
            "division": "East",
            "city": "Boston",
            "country": "USA",
            "abbreviation": "BOS",
        },
    },
    {
        "id": "baseball_team_toronto_blue_jays",
        "type": "team",
        "value": "Toronto Blue Jays",
        "aliases": [
            "Toronto Blue Jays",
            "Blue Jays",
            "Jays",
            "TOR",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "American League",
            "division": "East",
            "city": "Toronto",
            "country": "Canada",
            "abbreviation": "TOR",
        },
    },
    {
        "id": "baseball_team_baltimore_orioles",
        "type": "team",
        "value": "Baltimore Orioles",
        "aliases": [
            "Baltimore Orioles",
            "Orioles",
            "BAL",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "American League",
            "division": "East",
            "city": "Baltimore",
            "country": "USA",
            "abbreviation": "BAL",
        },
    },
    {
        "id": "baseball_team_tampa_bay_rays",
        "type": "team",
        "value": "Tampa Bay Rays",
        "aliases": [
            "Tampa Bay Rays",
            "Rays",
            "TB",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "American League",
            "division": "East",
            "city": "St. Petersburg",
            "country": "USA",
            "abbreviation": "TB",
        },
    },

    # ==========================================
    # American League Central
    # ==========================================
    {
        "id": "baseball_team_cleveland_guardians",
        "type": "team",
        "value": "Cleveland Guardians",
        "aliases": [
            "Cleveland Guardians",
            "Guardians",
            "CLE",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "American League",
            "division": "Central",
            "city": "Cleveland",
            "country": "USA",
            "abbreviation": "CLE",
        },
    },
    {
        "id": "baseball_team_detroit_tigers",
        "type": "team",
        "value": "Detroit Tigers",
        "aliases": [
            "Detroit Tigers",
            "Tigers",
            "DET",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "American League",
            "division": "Central",
            "city": "Detroit",
            "country": "USA",
            "abbreviation": "DET",
        },
    },
    {
        "id": "baseball_team_kansas_city_royals",
        "type": "team",
        "value": "Kansas City Royals",
        "aliases": [
            "Kansas City Royals",
            "Royals",
            "KC",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "American League",
            "division": "Central",
            "city": "Kansas City",
            "country": "USA",
            "abbreviation": "KC",
        },
    },
    {
        "id": "baseball_team_minnesota_twins",
        "type": "team",
        "value": "Minnesota Twins",
        "aliases": [
            "Minnesota Twins",
            "Twins",
            "MIN",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "American League",
            "division": "Central",
            "city": "Minneapolis",
            "country": "USA",
            "abbreviation": "MIN",
        },
    },
    {
        "id": "baseball_team_chicago_white_sox",
        "type": "team",
        "value": "Chicago White Sox",
        "aliases": [
            "Chicago White Sox",
            "White Sox",
            "CWS",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "American League",
            "division": "Central",
            "city": "Chicago",
            "country": "USA",
            "abbreviation": "CWS",
        },
    },

    # ==========================================
    # American League West
    # ==========================================
    {
        "id": "baseball_team_houston_astros",
        "type": "team",
        "value": "Houston Astros",
        "aliases": [
            "Houston Astros",
            "Astros",
            "HOU",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "American League",
            "division": "West",
            "city": "Houston",
            "country": "USA",
            "abbreviation": "HOU",
        },
    },
    {
        "id": "baseball_team_seattle_mariners",
        "type": "team",
        "value": "Seattle Mariners",
        "aliases": [
            "Seattle Mariners",
            "Mariners",
            "SEA",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "American League",
            "division": "West",
            "city": "Seattle",
            "country": "USA",
            "abbreviation": "SEA",
        },
    },
    {
        "id": "baseball_team_texas_rangers",
        "type": "team",
        "value": "Texas Rangers",
        "aliases": [
            "Texas Rangers",
            "Rangers",
            "TEX",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "American League",
            "division": "West",
            "city": "Arlington",
            "country": "USA",
            "abbreviation": "TEX",
        },
    },
    {
        "id": "baseball_team_los_angeles_angels",
        "type": "team",
        "value": "Los Angeles Angels",
        "aliases": [
            "Los Angeles Angels",
            "Angels",
            "LAA",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "American League",
            "division": "West",
            "city": "Anaheim",
            "country": "USA",
            "abbreviation": "LAA",
        },
    },
    {
        "id": "baseball_team_athletics",
        "type": "team",
        "value": "Athletics",
        "aliases": [
            "Athletics",
            "A's",
            "As",
            "ATH",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "American League",
            "division": "West",
            "city": "West Sacramento",
            "country": "USA",
            "abbreviation": "ATH",
        },
    },

    # ==========================================
    # National League East
    # ==========================================
    {
        "id": "baseball_team_atlanta_braves",
        "type": "team",
        "value": "Atlanta Braves",
        "aliases": [
            "Atlanta Braves",
            "Braves",
            "ATL",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "National League",
            "division": "East",
            "city": "Atlanta",
            "country": "USA",
            "abbreviation": "ATL",
        },
    },
    {
        "id": "baseball_team_new_york_mets",
        "type": "team",
        "value": "New York Mets",
        "aliases": [
            "New York Mets",
            "Mets",
            "NYM",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "National League",
            "division": "East",
            "city": "New York",
            "country": "USA",
            "abbreviation": "NYM",
        },
    },
    {
        "id": "baseball_team_philadelphia_phillies",
        "type": "team",
        "value": "Philadelphia Phillies",
        "aliases": [
            "Philadelphia Phillies",
            "Phillies",
            "PHI",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "National League",
            "division": "East",
            "city": "Philadelphia",
            "country": "USA",
            "abbreviation": "PHI",
        },
    },
    {
        "id": "baseball_team_miami_marlins",
        "type": "team",
        "value": "Miami Marlins",
        "aliases": [
            "Miami Marlins",
            "Marlins",
            "MIA",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "National League",
            "division": "East",
            "city": "Miami",
            "country": "USA",
            "abbreviation": "MIA",
        },
    },
    {
        "id": "baseball_team_washington_nationals",
        "type": "team",
        "value": "Washington Nationals",
        "aliases": [
            "Washington Nationals",
            "Nationals",
            "Nats",
            "WSH",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "National League",
            "division": "East",
            "city": "Washington",
            "country": "USA",
            "abbreviation": "WSH",
        },
    },

    # ==========================================
    # National League Central
    # ==========================================
    {
        "id": "baseball_team_chicago_cubs",
        "type": "team",
        "value": "Chicago Cubs",
        "aliases": ["Chicago Cubs", "Cubs", "CHC"],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "National League",
            "division": "Central",
            "city": "Chicago",
            "country": "USA",
            "abbreviation": "CHC",
        },
    },
    {
        "id": "baseball_team_cincinnati_reds",
        "type": "team",
        "value": "Cincinnati Reds",
        "aliases": ["Cincinnati Reds", "Reds", "CIN"],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "National League",
            "division": "Central",
            "city": "Cincinnati",
            "country": "USA",
            "abbreviation": "CIN",
        },
    },
    {
        "id": "baseball_team_milwaukee_brewers",
        "type": "team",
        "value": "Milwaukee Brewers",
        "aliases": ["Milwaukee Brewers", "Brewers", "MIL"],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "National League",
            "division": "Central",
            "city": "Milwaukee",
            "country": "USA",
            "abbreviation": "MIL",
        },
    },
    {
        "id": "baseball_team_pittsburgh_pirates",
        "type": "team",
        "value": "Pittsburgh Pirates",
        "aliases": ["Pittsburgh Pirates", "Pirates", "PIT"],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "National League",
            "division": "Central",
            "city": "Pittsburgh",
            "country": "USA",
            "abbreviation": "PIT",
        },
    },
    {
        "id": "baseball_team_st_louis_cardinals",
        "type": "team",
        "value": "St. Louis Cardinals",
        "aliases": [
            "St. Louis Cardinals",
            "Saint Louis Cardinals",
            "Cardinals",
            "STL",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "National League",
            "division": "Central",
            "city": "St. Louis",
            "country": "USA",
            "abbreviation": "STL",
        },
    },

    # ==========================================
    # National League West
    # ==========================================
    {
        "id": "baseball_team_los_angeles_dodgers",
        "type": "team",
        "value": "Los Angeles Dodgers",
        "aliases": [
            "Los Angeles Dodgers",
            "Dodgers",
            "LAD",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "National League",
            "division": "West",
            "city": "Los Angeles",
            "country": "USA",
            "abbreviation": "LAD",
        },
    },
    {
        "id": "baseball_team_san_diego_padres",
        "type": "team",
        "value": "San Diego Padres",
        "aliases": [
            "San Diego Padres",
            "Padres",
            "SD",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "National League",
            "division": "West",
            "city": "San Diego",
            "country": "USA",
            "abbreviation": "SD",
        },
    },
    {
        "id": "baseball_team_san_francisco_giants",
        "type": "team",
        "value": "San Francisco Giants",
        "aliases": [
            "San Francisco Giants",
            "Giants",
            "SF",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "National League",
            "division": "West",
            "city": "San Francisco",
            "country": "USA",
            "abbreviation": "SF",
        },
    },
    {
        "id": "baseball_team_arizona_diamondbacks",
        "type": "team",
        "value": "Arizona Diamondbacks",
        "aliases": [
            "Arizona Diamondbacks",
            "Diamondbacks",
            "D-backs",
            "ARI",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "National League",
            "division": "West",
            "city": "Phoenix",
            "country": "USA",
            "abbreviation": "ARI",
        },
    },
    {
        "id": "baseball_team_colorado_rockies",
        "type": "team",
        "value": "Colorado Rockies",
        "aliases": [
            "Colorado Rockies",
            "Rockies",
            "COL",
        ],
        "sport": "Baseball",
        "metadata": {
            "league": "MLB",
            "conference": "National League",
            "division": "West",
            "city": "Denver",
            "country": "USA",
            "abbreviation": "COL",
        },
    },
]