BASKETBALL_PLAYERS = [
    {
        "id": "basketball_player_lebron_james",
        "type": "player",
        "value": "LeBron James",
        "aliases": [
            "LeBron James",
            "LeBron",
            "King James",
        ],
        "sport": "Basketball",
        "metadata": {
            "team": "Los Angeles Lakers",
            "league": "NBA",
            "position": "Forward",
            "jersey": "23",
            "country": "USA",
            "height": "6 ft 9 in",
        },
    },
    {
        "id": "basketball_player_luka_doncic",
        "type": "player",
        "value": "Luka Dončić",
        "aliases": [
            "Luka Dončić",
            "Luka Doncic",
            "Luka",
        ],
        "sport": "Basketball",
        "metadata": {
            "team": "Los Angeles Lakers",
            "league": "NBA",
            "position": "Guard",
            "jersey": "77",
            "country": "Slovenia",
            "height": "6 ft 6 in",
        },
    },
    {
        "id": "basketball_player_stephen_curry",
        "type": "player",
        "value": "Stephen Curry",
        "aliases": [
            "Stephen Curry",
            "Steph Curry",
            "Steph",
            "Chef Curry",
        ],
        "sport": "Basketball",
        "metadata": {
            "team": "Golden State Warriors",
            "league": "NBA",
            "position": "Guard",
            "jersey": "30",
            "country": "USA",
            "height": "6 ft 2 in",
        },
    },
    {
        "id": "basketball_player_draymond_green",
        "type": "player",
        "value": "Draymond Green",
        "aliases": [
            "Draymond Green",
            "Draymond",
        ],
        "sport": "Basketball",
        "metadata": {
            "team": "Golden State Warriors",
            "league": "NBA",
            "position": "Forward",
            "jersey": "23",
            "country": "USA",
            "height": "6 ft 6 in",
        },
    },
    {
        "id": "basketball_player_jimmy_butler",
        "type": "player",
        "value": "Jimmy Butler",
        "aliases": [
            "Jimmy Butler",
            "Jimmy",
            "Jimmy Buckets",
        ],
        "sport": "Basketball",
        "metadata": {
            "team": "Golden State Warriors",
            "league": "NBA",
            "position": "Forward",
            "jersey": "10",
            "country": "USA",
            "height": "6 ft 7 in",
        },
    },
    {
        "id": "basketball_player_nikola_jokic",
        "type": "player",
        "value": "Nikola Jokić",
        "aliases": [
            "Nikola Jokić",
            "Nikola Jokic",
            "Jokic",
            "Joker",
        ],
        "sport": "Basketball",
        "metadata": {
            "team": "Denver Nuggets",
            "league": "NBA",
            "position": "Center",
            "jersey": "15",
            "country": "Serbia",
            "height": "6 ft 11 in",
        },
    },
    {
        "id": "basketball_player_jamal_murray",
        "type": "player",
        "value": "Jamal Murray",
        "aliases": [
            "Jamal Murray",
            "Murray",
        ],
        "sport": "Basketball",
        "metadata": {
            "team": "Denver Nuggets",
            "league": "NBA",
            "position": "Guard",
            "jersey": "27",
            "country": "Canada",
            "height": "6 ft 4 in",
        },
    },
    {
        "id": "basketball_player_giannis_antetokounmpo",
        "type": "player",
        "value": "Giannis Antetokounmpo",
        "aliases": [
            "Giannis Antetokounmpo",
            "Giannis",
            "Greek Freak",
        ],
        "sport": "Basketball",
        "metadata": {
            "team": "Milwaukee Bucks",
            "league": "NBA",
            "position": "Forward",
            "jersey": "34",
            "country": "Greece",
            "height": "6 ft 11 in",
        },
    },
    {
        "id": "basketball_player_damian_lillard",
        "type": "player",
        "value": "Damian Lillard",
        "aliases": [
            "Damian Lillard",
            "Dame",
            "Dame Time",
        ],
        "sport": "Basketball",
        "metadata": {
            "team": "Milwaukee Bucks",
            "league": "NBA",
            "position": "Guard",
            "jersey": "0",
            "country": "USA",
            "height": "6 ft 2 in",
        },
    },
    {
        "id": "basketball_player_jayson_tatum",
        "type": "player",
        "value": "Jayson Tatum",
        "aliases": [
            "Jayson Tatum",
            "Tatum",
        ],
        "sport": "Basketball",
        "metadata": {
            "team": "Boston Celtics",
            "league": "NBA",
            "position": "Forward",
            "jersey": "0",
            "country": "USA",
            "height": "6 ft 8 in",
        },
    },
    {
        "id": "basketball_player_jaylen_brown",
        "type": "player",
        "value": "Jaylen Brown",
        "aliases": [
            "Jaylen Brown",
            "Brown",
        ],
        "sport": "Basketball",
        "metadata": {
            "team": "Boston Celtics",
            "league": "NBA",
            "position": "Guard",
            "jersey": "7",
            "country": "USA",
            "height": "6 ft 6 in",
        },
    },
    {
        "id": "basketball_player_shai_gilgeous_alexander",
        "type": "player",
        "value": "Shai Gilgeous-Alexander",
        "aliases": [
            "Shai Gilgeous-Alexander",
            "Shai",
            "SGA",
        ],
        "sport": "Basketball",
        "metadata": {
            "team": "Oklahoma City Thunder",
            "league": "NBA",
            "position": "Guard",
            "jersey": "2",
            "country": "Canada",
            "height": "6 ft 6 in",
        },
    },
    {
        "id": "basketball_player_victor_wembanyama",
        "type": "player",
        "value": "Victor Wembanyama",
        "aliases": [
            "Victor Wembanyama",
            "Wembanyama",
            "Wemby",
        ],
        "sport": "Basketball",
        "metadata": {
            "team": "San Antonio Spurs",
            "league": "NBA",
            "position": "Center",
            "jersey": "1",
            "country": "France",
            "height": "7 ft 3 in",
        },
    },
    {
        "id": "basketball_player_anthony_edwards",
        "type": "player",
        "value": "Anthony Edwards",
        "aliases": [
            "Anthony Edwards",
            "Ant",
            "Ant Edwards",
        ],
        "sport": "Basketball",
        "metadata": {
            "team": "Minnesota Timberwolves",
            "league": "NBA",
            "position": "Guard",
            "jersey": "5",
            "country": "USA",
            "height": "6 ft 4 in",
        },
    },
    {
        "id": "basketball_player_anthony_davis",
        "type": "player",
        "value": "Anthony Davis",
        "aliases": [
            "Anthony Davis",
            "AD",
        ],
        "sport": "Basketball",
        "metadata": {
            "team": "Dallas Mavericks",
            "league": "NBA",
            "position": "Center / Forward",
            "jersey": "3",
            "country": "USA",
            "height": "6 ft 10 in",
        },
    },
    {
        "id": "basketball_player_kyrie_irving",
        "type": "player",
        "value": "Kyrie Irving",
        "aliases": [
            "Kyrie Irving",
            "Kyrie",
        ],
        "sport": "Basketball",
        "metadata": {
            "team": "Dallas Mavericks",
            "league": "NBA",
            "position": "Guard",
            "jersey": "11",
            "country": "USA",
            "height": "6 ft 2 in",
        },
    },
    {
        "id": "basketball_player_devin_booker",
        "type": "player",
        "value": "Devin Booker",
        "aliases": [
            "Devin Booker",
            "Book",
            "Booker",
        ],
        "sport": "Basketball",
        "metadata": {
            "team": "Phoenix Suns",
            "league": "NBA",
            "position": "Guard",
            "jersey": "1",
            "country": "USA",
            "height": "6 ft 6 in",
        },
    },
    {
        "id": "basketball_player_joel_embiid",
        "type": "player",
        "value": "Joel Embiid",
        "aliases": [
            "Joel Embiid",
            "Embiid",
        ],
        "sport": "Basketball",
        "metadata": {
            "team": "Philadelphia 76ers",
            "league": "NBA",
            "position": "Center",
            "jersey": "21",
            "country": "Cameroon",
            "height": "7 ft 0 in",
        },
    },
    {
        "id": "basketball_player_donovan_mitchell",
        "type": "player",
        "value": "Donovan Mitchell",
        "aliases": [
            "Donovan Mitchell",
            "Mitchell",
            "Spida",
        ],
        "sport": "Basketball",
        "metadata": {
            "team": "Cleveland Cavaliers",
            "league": "NBA",
            "position": "Guard",
            "jersey": "45",
            "country": "USA",
            "height": "6 ft 3 in",
        },
    },
    {
        "id": "basketball_player_ja_morant",
        "type": "player",
        "value": "Ja Morant",
        "aliases": [
            "Ja Morant",
            "Ja",
        ],
        "sport": "Basketball",
        "metadata": {
            "team": "Memphis Grizzlies",
            "league": "NBA",
            "position": "Guard",
            "jersey": "12",
            "country": "USA",
            "height": "6 ft 2 in",
        },
    },
]