BASKETBALL_TEAMS = [
    {
        "id": "basketball_team_boston_celtics",
        "type": "team",
        "value": "Boston Celtics",
        "aliases": [
            "Boston Celtics",
            "Celtics",
            "Boston",
            "BOS",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Eastern",
            "division": "Atlantic",
            "city": "Boston",
            "country": "USA",
            "abbreviation": "BOS",
            "arena": "TD Garden",
        },
    },
    {
        "id": "basketball_team_brooklyn_nets",
        "type": "team",
        "value": "Brooklyn Nets",
        "aliases": [
            "Brooklyn Nets",
            "Nets",
            "Brooklyn",
            "BKN",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Eastern",
            "division": "Atlantic",
            "city": "Brooklyn",
            "country": "USA",
            "abbreviation": "BKN",
            "arena": "Barclays Center",
        },
    },
    {
        "id": "basketball_team_new_york_knicks",
        "type": "team",
        "value": "New York Knicks",
        "aliases": [
            "New York Knicks",
            "Knicks",
            "NYK",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Eastern",
            "division": "Atlantic",
            "city": "New York",
            "country": "USA",
            "abbreviation": "NYK",
            "arena": "Madison Square Garden",
        },
    },
    {
        "id": "basketball_team_philadelphia_76ers",
        "type": "team",
        "value": "Philadelphia 76ers",
        "aliases": [
            "Philadelphia 76ers",
            "76ers",
            "Sixers",
            "PHI",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Eastern",
            "division": "Atlantic",
            "city": "Philadelphia",
            "country": "USA",
            "abbreviation": "PHI",
            "arena": "Wells Fargo Center",
        },
    },
    {
        "id": "basketball_team_toronto_raptors",
        "type": "team",
        "value": "Toronto Raptors",
        "aliases": [
            "Toronto Raptors",
            "Raptors",
            "TOR",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Eastern",
            "division": "Atlantic",
            "city": "Toronto",
            "country": "Canada",
            "abbreviation": "TOR",
            "arena": "Scotiabank Arena",
        },
    },
    {
        "id": "basketball_team_milwaukee_bucks",
        "type": "team",
        "value": "Milwaukee Bucks",
        "aliases": [
            "Milwaukee Bucks",
            "Bucks",
            "MIL",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Eastern",
            "division": "Central",
            "city": "Milwaukee",
            "country": "USA",
            "abbreviation": "MIL",
            "arena": "Fiserv Forum",
        },
    },
    {
        "id": "basketball_team_cleveland_cavaliers",
        "type": "team",
        "value": "Cleveland Cavaliers",
        "aliases": [
            "Cleveland Cavaliers",
            "Cavaliers",
            "Cavs",
            "CLE",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Eastern",
            "division": "Central",
            "city": "Cleveland",
            "country": "USA",
            "abbreviation": "CLE",
            "arena": "Rocket Arena",
        },
    },
    {
        "id": "basketball_team_chicago_bulls",
        "type": "team",
        "value": "Chicago Bulls",
        "aliases": [
            "Chicago Bulls",
            "Bulls",
            "CHI",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Eastern",
            "division": "Central",
            "city": "Chicago",
            "country": "USA",
            "abbreviation": "CHI",
            "arena": "United Center",
        },
    },
    {
        "id": "basketball_team_atlanta_hawks",
        "type": "team",
        "value": "Atlanta Hawks",
        "aliases": [
            "Atlanta Hawks",
            "Hawks",
            "ATL",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Eastern",
            "division": "Southeast",
            "city": "Atlanta",
            "country": "USA",
            "abbreviation": "ATL",
            "arena": "State Farm Arena",
        },
    },
    {
        "id": "basketball_team_miami_heat",
        "type": "team",
        "value": "Miami Heat",
        "aliases": [
            "Miami Heat",
            "Heat",
            "MIA",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Eastern",
            "division": "Southeast",
            "city": "Miami",
            "country": "USA",
            "abbreviation": "MIA",
            "arena": "Kaseya Center",
        },
    },
    {
        "id": "basketball_team_golden_state_warriors",
        "type": "team",
        "value": "Golden State Warriors",
        "aliases": [
            "Golden State Warriors",
            "Warriors",
            "Golden State",
            "GSW",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Western",
            "division": "Pacific",
            "city": "San Francisco",
            "country": "USA",
            "abbreviation": "GSW",
            "arena": "Chase Center",
        },
    },
    {
        "id": "basketball_team_los_angeles_lakers",
        "type": "team",
        "value": "Los Angeles Lakers",
        "aliases": [
            "Los Angeles Lakers",
            "LA Lakers",
            "Lakers",
            "LAL",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Western",
            "division": "Pacific",
            "city": "Los Angeles",
            "country": "USA",
            "abbreviation": "LAL",
            "arena": "Crypto.com Arena",
        },
    },
    {
        "id": "basketball_team_los_angeles_clippers",
        "type": "team",
        "value": "Los Angeles Clippers",
        "aliases": [
            "Los Angeles Clippers",
            "LA Clippers",
            "Clippers",
            "LAC",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Western",
            "division": "Pacific",
            "city": "Los Angeles",
            "country": "USA",
            "abbreviation": "LAC",
            "arena": "Intuit Dome",
        },
    },
    {
        "id": "basketball_team_phoenix_suns",
        "type": "team",
        "value": "Phoenix Suns",
        "aliases": [
            "Phoenix Suns",
            "Suns",
            "PHX",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Western",
            "division": "Pacific",
            "city": "Phoenix",
            "country": "USA",
            "abbreviation": "PHX",
            "arena": "PHX Arena",
        },
    },
    {
        "id": "basketball_team_sacramento_kings",
        "type": "team",
        "value": "Sacramento Kings",
        "aliases": [
            "Sacramento Kings",
            "Kings",
            "SAC",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Western",
            "division": "Pacific",
            "city": "Sacramento",
            "country": "USA",
            "abbreviation": "SAC",
            "arena": "Golden 1 Center",
        },
    },
    {
        "id": "basketball_team_dallas_mavericks",
        "type": "team",
        "value": "Dallas Mavericks",
        "aliases": [
            "Dallas Mavericks",
            "Mavericks",
            "Mavs",
            "DAL",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Western",
            "division": "Southwest",
            "city": "Dallas",
            "country": "USA",
            "abbreviation": "DAL",
            "arena": "American Airlines Center",
        },
    },
    {
        "id": "basketball_team_houston_rockets",
        "type": "team",
        "value": "Houston Rockets",
        "aliases": [
            "Houston Rockets",
            "Rockets",
            "HOU",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Western",
            "division": "Southwest",
            "city": "Houston",
            "country": "USA",
            "abbreviation": "HOU",
            "arena": "Toyota Center",
        },
    },
    {
        "id": "basketball_team_memphis_grizzlies",
        "type": "team",
        "value": "Memphis Grizzlies",
        "aliases": [
            "Memphis Grizzlies",
            "Grizzlies",
            "MEM",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Western",
            "division": "Southwest",
            "city": "Memphis",
            "country": "USA",
            "abbreviation": "MEM",
            "arena": "FedExForum",
        },
    },
    {
        "id": "basketball_team_denver_nuggets",
        "type": "team",
        "value": "Denver Nuggets",
        "aliases": [
            "Denver Nuggets",
            "Nuggets",
            "DEN",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Western",
            "division": "Northwest",
            "city": "Denver",
            "country": "USA",
            "abbreviation": "DEN",
            "arena": "Ball Arena",
        },
    },
    {
        "id": "basketball_team_minnesota_timberwolves",
        "type": "team",
        "value": "Minnesota Timberwolves",
        "aliases": [
            "Minnesota Timberwolves",
            "Timberwolves",
            "Wolves",
            "MIN",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Western",
            "division": "Northwest",
            "city": "Minneapolis",
            "country": "USA",
            "abbreviation": "MIN",
            "arena": "Target Center",
        },
    },
    {
        "id": "basketball_team_oklahoma_city_thunder",
        "type": "team",
        "value": "Oklahoma City Thunder",
        "aliases": [
            "Oklahoma City Thunder",
            "Thunder",
            "OKC",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Western",
            "division": "Northwest",
            "city": "Oklahoma City",
            "country": "USA",
            "abbreviation": "OKC",
            "arena": "Paycom Center",
        },
    },
    {
        "id": "basketball_team_portland_trail_blazers",
        "type": "team",
        "value": "Portland Trail Blazers",
        "aliases": [
            "Portland Trail Blazers",
            "Trail Blazers",
            "Blazers",
            "POR",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Western",
            "division": "Northwest",
            "city": "Portland",
            "country": "USA",
            "abbreviation": "POR",
            "arena": "Moda Center",
        },
    },
    {
        "id": "basketball_team_utah_jazz",
        "type": "team",
        "value": "Utah Jazz",
        "aliases": [
            "Utah Jazz",
            "Jazz",
            "UTA",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Western",
            "division": "Northwest",
            "city": "Salt Lake City",
            "country": "USA",
            "abbreviation": "UTA",
            "arena": "Delta Center",
        },
    },
    {
        "id": "basketball_team_san_antonio_spurs",
        "type": "team",
        "value": "San Antonio Spurs",
        "aliases": [
            "San Antonio Spurs",
            "Spurs",
            "SAS",
        ],
        "sport": "Basketball",
        "metadata": {
            "league": "NBA",
            "conference": "Western",
            "division": "Southwest",
            "city": "San Antonio",
            "country": "USA",
            "abbreviation": "SAS",
            "arena": "Frost Bank Center",
        },
    },
]